apiVersion: route.openshift.io/v1
kind: Route
metadata: 
  labels: 
    app.kubernetes.io/instance: xrhg3b51r-nodejs
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: xrhg3b51r-nodejs 
  name: xrhg3b51r-nodejs
spec:
  port:
    targetPort: 3001 
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: xrhg3b51r-nodejs
    weight: 100 
